/* eslint-disable no-undef */

const validate = require('../index')

test.each([
  [5, 'integer', true],
  [5.1, 'integer', false],
  ['5', 'integer', false],
  [true, 'integer', false],
  [{ v: 5 }, 'integer', false],
  [[5], 'integer', false],
  [null, 'integer', false],
  [5, 'number', true],
  [5.1, 'number', true],
  ['5', 'number', false],
  [true, 'number', false],
  [{ v: 5 }, 'number', false],
  [[5], 'number', false],
  [null, 'number', false],
  [5, 'string', false],
  [5.1, 'string', false],
  ['5', 'string', true],
  [true, 'string', false],
  [{ v: 5 }, 'string', false],
  [[5], 'string', false],
  [null, 'string', false],
  [5, 'boolean', false],
  [5.1, 'boolean', false],
  ['5', 'boolean', false],
  [true, 'boolean', true],
  [{ v: 5 }, 'boolean', false],
  [[5], 'boolean', false],
  [null, 'boolean', false],
  [5, 'object', false],
  [5.1, 'object', false],
  ['5', 'object', false],
  [true, 'object', false],
  [{ v: 5 }, 'object', true],
  [[5], 'object', false],
  [null, 'object', false],
  [5, 'array', false],
  [5.1, 'array', false],
  ['5', 'array', false],
  [true, 'array', false],
  [{ v: 5 }, 'array', false],
  [[5], 'array', true],
  [null, 'array', false],
  [5, 'null', false],
  [5.1, 'null', false],
  ['5', 'null', false],
  [true, 'null', false],
  [{ v: 5 }, 'null', false],
  [[5], 'null', false],
  [null, 'null', true]
])('validation: %s is %s: %s', (val, type, res) => {
  expect(validate({ val: { type } }, { val }, { exception: false })).toBe(res)
})
